### ISSUE TITLE
Head's up: master of mpfb2 now requires blender 4.1

### ISSUE THREAD

**Issue by joepal1976** [NitroxNova/Humanizer#12]
Not a bug or issue per se. I just want to hint that I've now merged the blender4 branch into master in the mpfb2 repo. This causes mpfb2 master to require at least blender 4.1.0. 

I have no idea if this causes any trouble with the Humanizer project. 

If the blender 3.6 code is still needed, it is available in a separate branch: https://github.com/makehumancommunity/mpfb2/tree/last_blender3_version

Don't hesitate to reach out if you need more info about any of the above.

**Comment by joepal1976** [comment]
Also, looking at the docs in the readme here... MakeClothes has now been integrated in MPFB2 and should no longer need a separate installation.

**Comment by matt-seaton** [comment]
thanks for the update.  we don't have any blender code in our project i don't think.  we just pull in the raw data files and use those. 
 ill try out the master branch of mpfb2 and see if i can get makeclothes working.  thanks for your work. it's a great project
