### ISSUE TITLE
version number in plugin.cfg

### ISSUE THREAD

**Issue by Ithamar** [NitroxNova/humanizer#16]
It would be great to update the version number in plugin.cfg (the version shown in the Godot Plugins tab) when doing a release. This would make it easier for people to track what version they have installed vs any new releases (currently when downloading the 1.0.0 beta release it lists "0.1" as version number...)

I know it isn't super-important right now, but as more releases happen it would really help!

**Comment by matt-seaton** [comment]
thank you for pointing this out.

**Comment by NitroxNova** [comment]
updated, thanks!
