### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by GeorgeS2019** [NitroxNova/humanizer#17]
https://github.com/met4citizen/TalkingHead/issues/34#issuecomment-2144344690

There are many features here, though in JavaScript, would be of interest to Godot4 community

Text to lipsync

**Comment by NitroxNova** [comment]
we already have lip sync working with various apps on the phone, you can access them from the authoring tab : )

**Comment by GeorgeS2019** [comment]
I have seen the video showing the lipsync..the TalkingHead has many ToDo on your list

**Comment by NitroxNova** [comment]
oh i see, youre working with AI to make the text to animations. thats actually really cool! but outside the scope of this project. it should be a different plugin that just feeds the arc-keys into humanizer i think..

**Comment by GeorgeS2019** [comment]
Here is the non AI for text to lipsync which is state of art that will helep your project

https://github.com/met4citizen/TalkingHead/blob/cf86ab31942bd0ee38d0e952214fcb1542dc0e67/modules/lipsync-en.mjs#L14-27

**Comment by NitroxNova** [comment]
oh yes this is very good thank you! i will see about integrating it, putting it on the to-do list for now
