### ISSUE TITLE
Shader limitations

### ISSUE THREAD

**Issue by Loudened** [NitroxNova/humanizer#20]
I just watched the update on EmberlightStudios channel and wanted to drop a note here.

- First, it's a shame you guys couldn't reach a compromise but these things happen. Humans can't always agree with eachother - if we did life would be bland and devoid of variety. Disagreement is as important in the world as agreement.
That said, in my humble opinion Humanizer was always NitroxNova's project. She's been working on this for well over a year and took it 80% of the way to where it is now. Where there's a stalemate her position should be the default. I actually noticed some weeks ago the EmberlightStudios channel had a bit too much of a "I am working on this / I did this" tone and not enough use of "we" and "us" for a collaboration from the outset. I hope you guys will remain civil and both continue working on this and sharing code, even if you maintain your own slightly different forks. After all,  you still share a common interest and goals.

- Second, I don't think the Godot shader system is as limiting as Matt seems to think.
The vertex position is just a Vector3 value, or 3 floating point values. You also have other built-ins available in the vertex shader such as NORMAL, TANGENT and BINORMAL and the vertex COLOR value which is a Vector4 (red, green, blue and alpha).
You can use any of these to pass data into your shader. First 3 you might actually need already for shading, but the vertex COLOR value is not really going to be used at all, so you can just put your original X,Y,Z vertex positions into the R,G,B channels with 0 for alpha and then use those values in your shader instead of the modified vertex positions.  Hope this is helpful.

**Comment by NitroxNova** [comment]
i really appreciate it :) yes the main concern is i dont want to include additional plugin requirements, ive been working on using the fragment shaders with a viewport to generate the procedural textures so hopefully i can get that added, just kind of burnt out and wanting to work on my other games for a bit
