### ISSUE TITLE
yo! , this looks really cool is there a way to reach you out? by mail

### ISSUE THREAD

**Issue by dolev146** [NitroxNova/humanizer#27]
I want to think if it would be better to use godot instead of threejs for this medical project

https://5pyzgn-5173.csb.app/

**Comment by NitroxNova** [comment]
i dont have much context from that link, looks like a rod and a cylinder, if you have a link to the wiki or something that would be better

**Comment by dolev146** [comment]
Yes exactly

It's a lead of pace maker for the heart

We are trying to have it in our reactjs app , I have a friend that does it currently in threejs but I was wondering if Godot might be better? Because as I see you have really great experience with it

**Comment by dolev146** [comment]
You are the first person I am able to interact with that has experience with Godot

**Comment by dolev146** [comment]
![image](https://github.com/user-attachments/assets/bc974793-eccf-4bb0-81f3-ffea7b3ccf70)

**Comment by dolev146** [comment]
The doctor should be able to press on the contact to activate them in terms of electrical 
Red is + 
Blue is -
And gravy is no electricity

**Comment by dolev146** [comment]
Contact is the gray thing

**Comment by dolev146** [comment]
> i dont have much context from that link, looks like a rod and a cylinder, if you have a link to the wiki or something that would be better

Would appreciate your opinion

**Comment by NitroxNova** [comment]
this is very interesting, but i'd have to know alot more about it.. i assume you are trying to simulate some kind of input/output or internal body conditions? godot is a physics engine with pretty good 3d capabilities so it could work for this

**Comment by dolev146** [comment]
I am available to talk if you want on Google Meet or something else

dolev146@gmail.com

**Comment by dolev146** [comment]
if this interest you

**Comment by dolev146** [comment]
yes I am trying to do a simulation for the doctor in the surgery room to assist him in controlling the stimulation of the pacemaker from the software

**Comment by dolev146** [comment]
I would like to see, only if you got the time and no pressure at all, how this kind of cylinder code would be in Godot so I will be able to compare to threejs
