### ISSUE TITLE
Import hangs on unhandled exception for PNG import issues 

### ISSUE THREAD

**Issue by RavinMaddHatter** [NitroxNova/humanizer#28]
When importing custom clothings from Make human, there are some PNGs that i found that are not formatted in your expected format.  When the import algorithm hits one of these it can hang.

`enerating material for elvs_dirty_lil_maid_bonnet
res://assets/clothes/elvs_dirty_lil_maid_bonnet/bonnettex1.png: Texture detected as used in 3D. Enabling mipmap generation and setting the texture compression mode to VRAM Compressed (S3TC/ETC/BPTC).`

Attempting to run further processes will result in the following message in console :
` Thread busy...  Try again after current task completes`

The only recovery is to hard crash Godot engine.

[elvs_ruffle_sleeve_peasant_blouse_1.zip](https://github.com/user-attachments/files/16913385/elvs_ruffle_sleeve_peasant_blouse_1.zip)

**Comment by NitroxNova** [comment]
you need to run the project > tools > humanizer > preprocessing tasks > import images as uncompressed
you may want to delete the .import file for the png first, although it should handle that.. 
im trying a different method for the material processing though so this might not be necessary in a later release, not sure

**Comment by RavinMaddHatter** [comment]
It seemed to resolve itself for other models, maybe this one hung for other
reasons. In the end I found 94 models that either hung or didn't import.
The PNG may be a red Herring feel free to close
