### ISSUE TITLE
OBJ fails import but still ends up in asset list

### ISSUE THREAD

**Issue by RavinMaddHatter** [NitroxNova/humanizer#29]
When importing some OBJs an error occurs in the obj_to_mesh.gd, yet the unusable mesh shows up in the drop downs. The only way to resolve this is to remove the files from the assets folder then restart godot. Assets will continue to import after this fine, so the error handling is partially working correctly.

`Generating material for culturalibre_cl_don_quixote_hat
  res://addons/humanizer/scripts/core/obj_to_mesh.gd:75 - Invalid access of index '3' on a base object of type: 'Array'.`

[culturalibre_cl_don_quixote_hat.zip](https://github.com/user-attachments/files/16913406/culturalibre_cl_don_quixote_hat.zip)

note: i am importing all of the assets and adding the tags for all of the assets for my own project, Reporting any bugs i find as i find them. So far 47/56 have worked with only changing the tag information. So good work.

**Comment by NitroxNova** [comment]
seems to be fixed now, feel free to reopen if not
