### ISSUE TITLE
Confusing code in cloth_inspector.gd

### ISSUE THREAD

**Issue by Kiryonn** [NitroxNova/Humanizer#3]
[cloth_inspector.gd line 119](https://github.com/NitroxNova/Humanizer/blob/master/addons/humanizer/scripts/inspector/clothes_inspector.gd?plain=1#L119)
```gd
if config != null and not config.clothes.has(name):
	var clothes: HumanClothes = HumanizerRegistry.clothes[name]
	for sl in slots:
		last_equipped[sl] = clothes
	clothes_changed.emit(clothes)
	_material_selected(0, slot)
```

I have forked your project and i'm trying to inprove performances here and there. The first thing i did was starting to strongly type what wasn't, which also help me understand what you're doing in the code. But i've seen an error `Attempted to use 'has' a variable of type 'String' into a TypedArray of type 'Object'.`

Which made me look at the [cloth_inspector.gd](https://github.com/NitroxNova/Humanizer/blob/master/addons/humanizer/scripts/inspector/clothes_inspector.gd) code and i'm confused since from what i understand, clothes is an `Array<HumanClothes>` but is called as a `Dictionary<String, HumanClothes>`.

**Comment by matt-seaton** [comment]
Arrays have a "has" method.

https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-has

**Comment by matt-seaton** [comment]
I made some changes to this code, which is confusing to me also.  Try the latest commit and see if you still see the error.

**Comment by Kiryonn** [comment]
> Arrays have a "has" method.

Yeah I know, that's why it's confusing. The variable `name` is used with the has method for both the array and the dict which would mean it has 2 different types at the same time.


> I don't understand the error message. I have not seen this one.

I have a hunch on what it might be. But before I say anything I need to open the project again which might not happen before the week end.

**Comment by matt-seaton** [comment]
Ok.  Yes, this is a mistake.  The list does not contain strings so this expression would simply always evaluate to true.  The idea is that I didn't want to emit the signal if it's trying to equip clothes which are already equipped. This shouldn't happen anyway, but I will change the code to look up the resource by name from the registry.  Thanks.
