### ISSUE TITLE
Exporting has issues

### ISSUE THREAD

**Issue by RavinMaddHatter** [NitroxNova/humanizer#31]
I am working through exporting a binary based upon your example project. I dont know if you have successfully made an exe or other file. but i am struggling because the skelleton (along with many other resources) are not loading after exporting.

If you have had a successful export let me know what your settings are please. I have tried a few.

**Comment by RavinMaddHatter** [comment]
Okay... so it looks like when you compile .tscn files get renamed to .tscn.remap

```
static func load_asset(path : String) -> Resource:
    if OS.has_feature("export"):
        # Check if file is .remap
        if not path.ends_with(".remap"):
            return load(path)

        # Open the file
        var __config_file = ConfigFile.new()
        __config_file.load(path)

        # Load the remapped file
        var __remapped_file_path = __config_file.get_value("remap", "path")
        __config_file = null
        return load(__remapped_file_path)
    else:
        return load(path)
        ```
 
i am going to spend some time trying to fix this...

**Comment by NitroxNova** [comment]
no i have not yet tried to export, thank you for pointing this out as it is a high priority, let me know if you make any progress

**Comment by NitroxNova** [comment]
thank you for the links, very much appreciated! i tried the setting as you said and it did work, not really sure what that means or why it would make a difference but thank you again. are there any drawbacks to doing it this way?

**Comment by RavinMaddHatter** [comment]
It isn't as efficient to run. And the file is number.. The fix would be to
replace the load (string) with a new function that loads either the text
file or the compiled file

**Comment by NitroxNova** [comment]
ok, i was able to track down the issues using your initial leads, ended up changing the .tres files to .res and then i did a bit of a hack to register the .tscn files but the good news is the export works with default settings, i set the 'stress_test' scene as main scene, and am using debian linux. so let me know if the latest changes resolved the issue for you as well

**Comment by RavinMaddHatter** [comment]
Thank you! Will check when I get a chance

**Comment by NitroxNova** [comment]
alright i'll assume its working, thank you for helping me get that figured out and feel free to open another if its still having issues :)
