### ISSUE TITLE
Errors at runtime and unable to see AutoUpdatingHumanizer in node explorer

### ISSUE THREAD

**Issue by Abakus2k** [NitroxNova/humanizer#35]
Hello, very nice work with the godot plugin. Been using MakeHuman and MPFB until I saw your plugin for Godot.
Earlier versions worked quite good but Im unable to use the current 2.0 release or master build of Humanizer.
Im running Godot 4.3.stable on Windows 11 (yea, i know... :/ )

My steps and issues were the following:

1. Download humanizer master / 2.0 release
2. Create new Godot 3.4.stable Project and keep Godot open
3. Unpack humanizer archive
4. Create folder _addons_ in the godot projects
5. Copy the unpacked archive and rename to _humanizer_

After Godot automatically reimporting assets due to plugin installation:
```
  scene/resources/3d/importer_mesh.cpp:521 - Ignoring face with non-finite normal in LOD generation.
  Could not create child process:  --pbr-metallic-roughness --input D:/Workspaces/Godot/humanizer_test_master/addons/humanizer/data/animations/mixamo_reduced.fbx --output D:/Workspaces/Godot/humanizer_test_master/.godot/imported/mixamo_reduced-799d6ad60fb1236097e6a6b045b3670c.glb --binary
  modules/gltf/gltf_document.cpp:7419 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://addons/humanizer/data/animations/mixamo_reduced.fbx'.
  Failed loading resource: res://addons/humanizer/data/animations/mixamo_reduced.fbx. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/packed_scene.cpp:2171 - Condition "packed_scene.is_null()" is true. Returning: HashSet<StringName>()
  Cannot open file 'res://humanizer_global_config.res'.
  Failed loading resource: res://humanizer_global_config.res. Make sure resources have been imported by opening the project in the editor at least once.
  res://addons/humanizer/scripts/core/humanizer_registry.gd:35 - Invalid access to property or key 'asset_import_paths' on a base object of type 'Nil'.
  res://addons/humanizer/scripts/core/humanizer_registry.gd:73 - Invalid access to property or key 'asset_import_paths' on a base object of type 'Nil'.
  res://addons/humanizer/scripts/core/humanizer_registry.gd:60 - Invalid access to property or key 'asset_import_paths' on a base object of type 'Nil'.

```
The 2.0 build also throws an error here, which seems to have been resolved in master:
`scene/resources/packed_scene.cpp:2171 - Condition "packed_scene.is_null()" is true. Returning: HashSet<StringName>()`

6. Enable Project Settings->Plugins->Humanizer
7. Check Project Settings->Globals HumanizerGlobal is Enabled

Each type into the search bar throws the following Error:
`editor/create_dialog.cpp:272 - Condition "inherits == StringName()" is true.`
 
Im unable to see the the AutoUpdatingHumanizer Node in the Node Explorer:
![image](https://github.com/user-attachments/assets/ef9a0ea5-968f-4dfd-8a65-8879714d887c)

Loading a Humanizer node throws this error:
`editor/scene_tree_dock.cpp:2767 - Parameter "child" is null.`

Reloading the project also doesnt help and a mate of mine tried it out on his linux distro and ran into the same issues.

Am I doing anything wrong? Would you have any guidance in how to resolve this issue?
If any other logs or data is required Im happy to provide it.

**Comment by RavinMaddHatter** [comment]
Did you reload project or restart Godot after enabling things

**Comment by Abakus2k** [comment]
Yes, Ive tried that.
It resolves the import errors on startup but 
`editor/create_dialog.cpp:272 - Condition "inherits == StringName()" is true.`
still gets thrown when searching in the Node Explorer and the same nodes are visible as in the provided screenshot.
My Godot is freshly installed without any other plugins

**Comment by NitroxNova** [comment]
that you for the feedback! so the node you are looking for is the 'Humanizer Editor Tool' which is there in your screenshot, let me know if that works. the Humanizer class is just a resource so you cant add it to the scene, and most of those errors are expected on first time launch

**Comment by Abakus2k** [comment]
Thanks for the quick reply, it seems to be working fine with that Node.
`editor/create_dialog.cpp:272 - Condition "inherits == StringName()" is true.` still gets thrown with every type in searchbar, but I can happily ignore that.
Now I get `Invalid access to property or key of type 'String' on a base object of type 'Dictionary'.` at equipment.gd:12 and :21 when running a scene with a basic human, but this probably is another issue on my end. (in 2.0 release)

**Comment by NitroxNova** [comment]
you dont run the humanizer editor tool node, you can but its better to just make a Human_Config and use the Humanizer class to build it, ive been making alot of changes still but you can see an example of that in the scenes/tests/CharacterBody3D scene

**Comment by aldebaranzbradaradjan** [comment]
Hi, it should be nice to reopen this issue i think;
I face the very same error when i take a Human_Config and use the Humanizer class to build it.

More in depth, this work (from CharacterBody3D) :
```
extends Node3D

# Called when the node enters the scene tree for the first time.
func _ready():
	var config = HumanConfig.new()
	config.init_macros()
	config.targets['gender'] = 0
	config.targets['age'] = 25
	config.eye_color = Color.YELLOW
	config.hair_color = Color.PURPLE
	config.eyebrow_color = Color("550055")
	config.rig = HumanizerGlobalConfig.config.default_skeleton
	config.add_equipment(HumanizerEquipment.new("DefaultBody","young_caucasian_female2_diffuse"))
	config.add_equipment(HumanizerEquipment.new("SkinnyJeans"))
	config.add_equipment(HumanizerEquipment.new("MakeHumanTShirt"))
	config.add_equipment(HumanizerEquipment.new("Shoes02"))
	config.add_equipment(HumanizerEquipment.new("RightEyeball-LowPoly"))
	config.add_equipment(HumanizerEquipment.new("LeftEyeBall-LowPoly"))
	config.add_equipment(HumanizerEquipment.new("Bob02"))
	config.add_equipment(HumanizerEquipment.new("RightEyebrow-002"))
	config.add_equipment(HumanizerEquipment.new("LeftEyebrow-002"))
	config.add_equipment(HumanizerEquipment.new("RightEyelash"))
	config.add_equipment(HumanizerEquipment.new("LeftEyelash"))
	var humanizer = Humanizer.new(config)
	var char = humanizer.get_CharacterBody3D(false) ## can bake character here by setting argument to true
	add_child(char)
	HumanizerUtils.set_node_owner(char,self)
```

But this don't work :

```
extends Node3D
@export var human_config: HumanConfig

func _ready() -> void:
	var humanizer = Humanizer.new(human_config)
	var char = humanizer.get_CharacterBody3D(false) ## can bake character here by setting argument to true
	add_child(char)
	HumanizerUtils.set_node_owner(char,self)
```
	
I setted in human_config export field a .res obtained from the export in authoring scene, the program output :

> Invalid access to property or key of type 'String' on a base object of type 'Dictionary'

I also tried to set human_config like these :
`var human_config = load("res://data/humans/beautifull_red_braid/config_beautifull_red_braid.res")`

Without much change.

So, my question : It is a bug or i don't do the right thing ? There is an other way to load a config and create a character ?
Thanks in advance, and thanks again for your dedicated work !

**Comment by aldebaranzbradaradjan** [comment]
After research, i have found some details, first it seems you have already fixed Invalid access to property or key of type 'String' on a base object of type 'Dictionary' issue, in a recent commit; I have been able to pass this error by replacing content of equipment.gd with the last version on main ( the rest is the latest release).
But its not sufficient, i need to 
it work to load human config if i do like this :

extends Node3D
# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	var config = load("res://data/humans/beautifull_red_braid/config_beautifull_red_braid.res")
	config.rig = HumanizerGlobalConfig.config.default_skeleton
	var humanizer = Humanizer.new(config)
	var char = humanizer.get_CharacterBody3D(false) ## can bake character here by setting argument to true
	add_child(char)
	HumanizerUtils.set_node_owner(char,self)
