### ISSUE TITLE
[Help] How do I load a baked human

### ISSUE THREAD

**Issue by sagersmith8** [NitroxNova/Humanizer#9]
### Description
I am having a problem trying to load an already saved human, I am getting an error `Invalid get index 'mesh' (on base: 'Nil').`

### Steps to reproduce
1. Create a human using the humanizer node in a scene. Here are screenshots of my configuration:
![Screenshot 2024-04-28 at 10 42 11 AM](https://github.com/NitroxNova/Humanizer/assets/10541522/5115f19f-2126-4438-9c9d-943a8a882382)
![Screenshot 2024-04-28 at 10 42 34 AM](https://github.com/NitroxNova/Humanizer/assets/10541522/17940416-ec53-4e37-a014-7d4e2c57caae)

2. Bake the human, I hit `Save To File` Here is the output:
![Screenshot 2024-04-28 at 10 38 54 AM](https://github.com/NitroxNova/Humanizer/assets/10541522/e1e30107-1669-483b-ab4c-7a7c76f97c79)
3. Comment out [`reset_human()`](https://github.com/NitroxNova/Humanizer/blob/1c7f9ab184550812e8f3692d3e9dc050902aeb32/scripts/humanizer.gd#L193)
4. Load and run the stress test scene

**Comment by NitroxNova** [comment]
you can open the MyHuman.tscn on its own, or add it to another scene, no need for the stress tester

**Comment by sagersmith8** [comment]
No, @NitroxNova I get Invalid call. `Nonexistent function 'set_motor' in base 'Nil'. on like 51`. Its very possible that I misconfigured it though

**Comment by matt-seaton** [comment]
you cannot comment out reset_human().  it is there for a reason and everything will break without it.  i don't know what you are trying to achieve or what problems you are having,

we need the script files where the errors are occurring, not just the line number.  the stress test scene loads random humans.  it is not set up to load any human you have baked and saved to a file.

saved humans are meant to exist in their own scenes, independent of the stress test scene, the authoring scene, or any humanizer nodes.

**Comment by sagersmith8** [comment]
Here, I'll reset and try it again just a sec

**Comment by sagersmith8** [comment]
I am unable to run a scene using this character that I exported. It fails in` _physics_process`
[MyHuman.zip](https://github.com/NitroxNova/Humanizer/files/15143625/MyHuman.zip)

**Comment by sagersmith8** [comment]
I put a bad script on my character, my bad :) I didn't even realize, thanks for the support
